scan_to_scan_filter_chain:
  ros__parameters:
    filter1:
      name: range_filter
      type: laser_filters/LaserScanRangeFilter
      params:
        use_message_range_limits: false
        lower_threshold: 0.50
        upper_threshold: 2.5
        lower_replacement_value: .inf
        upper_replacement_value: .inf
